[project]
name = "skillnest-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cesar Marin Coopeuch", email = "cmarin.externo@coopeuch.cl" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.4",
    "google-genai>=2.29.0",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
skillnest-app = "skillnest_app:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
